<?php

declare(strict_types=1);

require_once __DIR__ . '/../src/Config.php';
require_once __DIR__ . '/../src/UserStore.php';

$root = dirname(__DIR__);

function install_default(string $key, string $default): string
{
    return Config::get($key, $default) ?? $default;
}

function install_write_env(string $root, array $values): void
{
    $lines = [
        '# Generated by FaceAuth Backend installer on ' . gmdate('c'),
        'FACEAUTH_CORE_URL=' . $values['core_url'],
        'FACEAUTH_TENANT_ID=' . $values['tenant_id'],
        'FACEAUTH_TENANT_SECRET=' . $values['tenant_secret'],
        'FACEAUTH_MOODLE_SHARED_SECRET=' . $values['moodle_shared_secret'],
        'FACEAUTH_STORAGE_PHOTOS=' . $values['storage_photos'],
        'FACEAUTH_STORAGE_LOGS=' . $values['storage_logs'],
        'FACEAUTH_LICENSE_CACHE=' . $values['license_cache'],
        'FACEAUTH_USERS_FILE=' . $values['users_file'],
    ];

    $env = implode(PHP_EOL, $lines) . PHP_EOL;
    $path = $root . '/.env';
    if (file_put_contents($path, $env, LOCK_EX) === false) {
        throw new RuntimeException('Could not write .env file');
    }
    chmod($path, 0660);
}

function install_value(string $key, string $default): string
{
    return trim((string)($_POST[$key] ?? $default));
}

$defaults = [
    'core_url' => install_default('FACEAUTH_CORE_URL', 'https://core.example.com'),
    'tenant_id' => install_default('FACEAUTH_TENANT_ID', 'tenant_demo'),
    'tenant_secret' => install_default('FACEAUTH_TENANT_SECRET', 'tenant_demo_secret'),
    'moodle_shared_secret' => install_default('FACEAUTH_MOODLE_SHARED_SECRET', bin2hex(random_bytes(16))),
    'storage_photos' => install_default('FACEAUTH_STORAGE_PHOTOS', $root . '/storage/photos'),
    'storage_logs' => install_default('FACEAUTH_STORAGE_LOGS', $root . '/storage/logs'),
    'license_cache' => install_default('FACEAUTH_LICENSE_CACHE', $root . '/storage/license-cache.json'),
    'users_file' => install_default('FACEAUTH_USERS_FILE', $root . '/storage/users.json'),
];

$values = $defaults;
$store = new UserStore($defaults['users_file']);
$installed = $store->isInstalled();
$error = '';
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$installed) {
    $values = [
        'core_url' => install_value('core_url', $defaults['core_url']),
        'tenant_id' => install_value('tenant_id', $defaults['tenant_id']),
        'tenant_secret' => install_value('tenant_secret', $defaults['tenant_secret']),
        'moodle_shared_secret' => install_value('moodle_shared_secret', $defaults['moodle_shared_secret']),
        'storage_photos' => install_value('storage_photos', $defaults['storage_photos']),
        'storage_logs' => install_value('storage_logs', $defaults['storage_logs']),
        'license_cache' => install_value('license_cache', $defaults['license_cache']),
        'users_file' => install_value('users_file', $defaults['users_file']),
    ];

    $superadminUser = trim((string)($_POST['superadmin_user'] ?? ''));
    $superadminPassword = (string)($_POST['superadmin_password'] ?? '');
    $universityAdminUser = trim((string)($_POST['admin_user'] ?? ''));
    $universityAdminPassword = (string)($_POST['admin_password'] ?? '');

    try {
        foreach (['core_url', 'tenant_id', 'tenant_secret', 'moodle_shared_secret', 'storage_photos', 'storage_logs', 'license_cache', 'users_file'] as $required) {
            if ($values[$required] === '') {
                throw new RuntimeException($required . ' is required');
            }
        }

        if (!is_dir($values['storage_photos'])) {
            mkdir($values['storage_photos'], 0770, true);
        }
        if (!is_dir($values['storage_logs'])) {
            mkdir($values['storage_logs'], 0770, true);
        }

        install_write_env($root, $values);

        $store = new UserStore($values['users_file']);
        $store->createInitialUsers($superadminUser, $superadminPassword, $universityAdminUser, $universityAdminPassword);
        $success = true;
        $installed = true;
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

header('Content-Type: text/html; charset=utf-8');
?>
<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FaceAuth Backend Installer</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.5; margin: 32px; max-width: 920px; }
    .card { border: 1px solid #ddd; border-radius: 8px; margin: 16px 0; padding: 16px; }
    .grid { display: grid; gap: 12px; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); }
    label { display: flex; flex-direction: column; margin: 10px 0; }
    input { font-size: 16px; padding: 8px; }
    button { font-size: 16px; padding: 10px 14px; }
    .error { background: #ffecec; border-color: #e5a0a0; }
    .success { background: #ecfff1; border-color: #9ed3aa; }
    code { background: #f5f5f5; padding: 2px 5px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>Установка FaceAuth Backend</h1>

  <?php if ($success): ?>
    <div class="card success">
      <strong>Готово.</strong> `.env`, storage-директории и пользователи созданы. Перейдите в <a href="/admin/index.php">панель управления</a> и войдите под superadmin.
    </div>
  <?php elseif ($installed): ?>
    <div class="card success">
      Backend уже установлен. Перейдите в <a href="/admin/index.php">панель управления</a>.
    </div>
  <?php else: ?>
    <?php if ($error !== ''): ?>
      <div class="card error"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div>
    <?php endif; ?>

    <form method="post">
      <div class="card">
        <h2>1. Конфигурация подключения</h2>
        <div class="grid">
          <label>Core URL <input name="core_url" required value="<?= htmlspecialchars($values['core_url'], ENT_QUOTES, 'UTF-8') ?>"></label>
          <label>Tenant ID <input name="tenant_id" required value="<?= htmlspecialchars($values['tenant_id'], ENT_QUOTES, 'UTF-8') ?>"></label>
          <label>Tenant secret <input name="tenant_secret" required value="<?= htmlspecialchars($values['tenant_secret'], ENT_QUOTES, 'UTF-8') ?>"></label>
          <label>Moodle shared secret <input name="moodle_shared_secret" required value="<?= htmlspecialchars($values['moodle_shared_secret'], ENT_QUOTES, 'UTF-8') ?>"></label>
        </div>
      </div>

      <div class="card">
        <h2>2. Пути хранения</h2>
        <p>Для shared hosting лучше использовать абсолютные пути.</p>
        <div class="grid">
          <label>Photos directory <input name="storage_photos" required value="<?= htmlspecialchars($values['storage_photos'], ENT_QUOTES, 'UTF-8') ?>"></label>
          <label>Logs directory <input name="storage_logs" required value="<?= htmlspecialchars($values['storage_logs'], ENT_QUOTES, 'UTF-8') ?>"></label>
          <label>License cache file <input name="license_cache" required value="<?= htmlspecialchars($values['license_cache'], ENT_QUOTES, 'UTF-8') ?>"></label>
          <label>Users file <input name="users_file" required value="<?= htmlspecialchars($values['users_file'], ENT_QUOTES, 'UTF-8') ?>"></label>
        </div>
      </div>

      <div class="card">
        <h2>3. Пользователи панели</h2>
        <p>
          Installer создаёт локальных пользователей панели: <code>superadmin</code> для управления backend
          и <code>admin</code> для университетской системы. Пароли сохраняются только как password hash.
        </p>
        <div class="grid">
          <label>Логин superadmin <input name="superadmin_user" required autocomplete="username" value="superadmin"></label>
          <label>Пароль superadmin <input name="superadmin_password" type="password" required minlength="8" autocomplete="new-password"></label>
          <label>Логин админа университета <input name="admin_user" required autocomplete="username" value="university_admin"></label>
          <label>Пароль админа университета <input name="admin_password" type="password" required minlength="8" autocomplete="new-password"></label>
        </div>
        <button type="submit">Установить FaceAuth Backend</button>
      </div>
    </form>
  <?php endif; ?>
</body>
</html>
